

$rgName = "vh-packer-image"
$location = "UK South"



$timestamp = Get-Date -Format yyyyMMddHHMMss 
 & packer build -machine-readable `
 -var "time_stamp=$timestamp" `
 -var-file AAD_Variables.json `
  windowsagent.json



  <#

Skus                                           Offer                   PublisherName          Location Id
----                                           -----                   -------------          -------- --
Datacenter-Core-1709-smalldisk                 WindowsServerSemiAnnual MicrosoftWindowsServer uksouth  /Subscription...
Datacenter-Core-1709-with-Containers-smalldisk WindowsServerSemiAnnual MicrosoftWindowsServer uksouth  /Subscription...
Datacenter-Core-1803-with-Containers-smalldisk WindowsServerSemiAnnual MicrosoftWindowsServer uksouth  /Subscription...
2008-R2-SP1                           windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2008-R2-SP1-smalldisk                 windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2012-Datacenter                       windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2012-Datacenter-smalldisk             windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2012-R2-Datacenter                    windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2012-R2-Datacenter-smalldisk          windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2016-Datacenter                       windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2016-Datacenter-Server-Core           windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2016-Datacenter-Server-Core-smalldisk windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2016-Datacenter-smalldisk             windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2016-Datacenter-with-Containers       windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
2016-Nano-Server                      windowsserver MicrosoftWindowsServer uksouth  /Subscriptions/bf308a5c-0624-433...
#>