parameters:
  workingDirectory: $(system.defaultWorkingDirectory)
  pool:
  environments: []
  jobs: []
  pat_token: ""
  agent_pool: ""

jobs:
- ${{ each deployment in parameters.environments }}:
  - deployment: Build_Agent_${{ deployment.name }}

    pool:
      name: ${{ parameters.pool }}

    environment: ${{ deployment.name }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true
            
          - template: terraform-deploy.yml
            parameters:
              workingDirectory: ${{ parameters.workingDirectory }}
              storageAccount: ${{ deployment.storageAccount }}
              environment: ${{ deployment.name }}
              armServiceConnection: ${{ deployment.armServiceConnection }}
              pat_token: ${{ parameters.pat_token }}
              agent_pool: ${{ parameters.agent_pool }}
